// Interface Runtime Support - Implementation
// This file provides runtime support for interface dynamic dispatch
// DO NOT EDIT - This file is automatically generated

// ============================================================================
// Interface Value Operations
// ============================================================================

// Create a new interface value by wrapping a concrete struct
// The concrete struct is copied to the heap
nx_interface_value* nx_interface_wrap(void* concrete_data, size_t data_size, nx_vtable_base* vtable) {
    nx_interface_value* iface = (nx_interface_value*)nx_malloc(sizeof(nx_interface_value));
    iface->data = nx_malloc(data_size);
#ifdef _WIN32
    memcpy_s(iface->data, data_size, concrete_data, data_size);
#else
    memcpy(iface->data, concrete_data, data_size);
#endif
    iface->data_size = data_size;
    iface->vtable = vtable;
    return iface;
}

// Create an interface value on the stack (data is NOT copied, just referenced)
// Use this for temporary interface values that don't outlive the concrete data
nx_interface_value nx_interface_wrap_stack(void* concrete_data, size_t data_size, nx_vtable_base* vtable) {
    nx_interface_value iface;
    iface.data = concrete_data;
    iface.data_size = data_size;
    iface.vtable = vtable;
    return iface;
}

// Get the concrete data from an interface value (for field access)
void* nx_interface_unwrap(nx_interface_value* iface) {
    if (iface == NULL) {
        nx_panic("Cannot unwrap NULL interface value");
    }
    return iface->data;
}

// Get the vtable from an interface value
nx_vtable_base* nx_interface_get_vtable(nx_interface_value* iface) {
    if (iface == NULL) {
        nx_panic("Cannot get vtable from NULL interface value");
    }
    return iface->vtable;
}

// Free an interface value (frees the copied data)
void nx_interface_free(nx_interface_value* iface) {
    if (iface != NULL) {
        if (iface->data != NULL) {
            nx_free(iface->data);
        }
        nx_free(iface);
    }
}