//! Runtime support code generator for Nexus C transpilation.
//!
//! This module generates the nexus_core.c and nexus_core.h files that provide
//! runtime support for transpiled Nexus code, including compat/plat functionality.

use crate::TranspilerConfig;

/// Generate the nexus_core.h header file
pub const RUNTIME_HEADER: &str = include_str!("runtime_includes/nexus_core.h");

/// Generate the nexus_core.c implementation file
pub fn generate_runtime(config: &TranspilerConfig) -> String {
    let error_handling = if config.bounds_checking {
        include_str!("runtime_includes/error.c")
    } else {
        include_str!("runtime_includes/error_nobounds.c")
    };

    format!(
        r#"// Nexus Runtime Core - Implementation
// This file provides runtime support for transpiled Nexus code
// DO NOT EDIT - This file is automatically generated

{}

{}

{}

{}

{}

{}

{}

{}

{}
"#,
        include_str!("runtime_includes/memory.c"),
        include_str!("runtime_includes/array.c"),
        include_str!("runtime_includes/string.c"),
        include_str!("runtime_includes/unknown.c"),
        error_handling,
        include_str!("runtime_includes/compat_io.c"),
        include_str!("runtime_includes/compat_time.c"),
        include_str!("runtime_includes/compat_process.c"),
        include_str!("runtime_includes/platform.c"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_runtime_header() {
        assert!(RUNTIME_HEADER.contains("nexus_core.h"));
        assert!(RUNTIME_HEADER.contains("nx_malloc"));
        assert!(RUNTIME_HEADER.contains("nx_array"));
        assert!(
            RUNTIME_HEADER.contains("// Convert a typed value to string (recursive for arrays)")
        );
    }

    #[test]
    fn test_generate_runtime_with_bounds_checking() {
        let config = TranspilerConfig {
            bounds_checking: true,
            ..Default::default()
        };
        let runtime = generate_runtime(&config);
        assert!(runtime.contains("nx_bounds_check"));
        assert!(runtime.contains("Bounds check failed"));
    }

    #[test]
    fn test_generate_runtime_without_bounds_checking() {
        let config = TranspilerConfig {
            bounds_checking: false,
            ..Default::default()
        };
        let runtime = generate_runtime(&config);
        assert!(runtime.contains("Bounds checking disabled"));
    }

    #[test]
    fn test_runtime_has_recursive_array_handling() {
        let config = TranspilerConfig::default();
        let runtime = generate_runtime(&config);

        // Check for recursive array handling function
        assert!(runtime.contains("nx_string_from_array_recursive"));

        // Check for depth parameter to prevent infinite recursion
        assert!(runtime.contains("int depth"));

        // Check for nested array handling
        assert!(runtime.contains("Nested array"));

        // Check for recursive call
        assert!(runtime.contains("depth + 1"));
    }

    #[test]
    fn test_runtime_uses_memcpy_s() {
        let config = TranspilerConfig::default();
        let runtime = generate_runtime(&config);

        // Check for memcpy_s usage on Windows
        assert!(runtime.contains("#ifdef _WIN32"));
        assert!(runtime.contains("memcpy_s"));

        // Check for fallback to memcpy on other platforms
        assert!(runtime.contains("#else"));
        assert!(runtime.contains("memcpy("));
    }

    #[test]
    fn test_runtime_includes_all_modules() {
        let config = TranspilerConfig::default();
        let runtime = generate_runtime(&config);

        // Verify all major sections are included
        assert!(runtime.contains("Memory Management"));
        assert!(runtime.contains("Dynamic Arrays"));
        assert!(runtime.contains("Strings"));
        assert!(runtime.contains("Unknown/Sum Types"));
        assert!(runtime.contains("Error Handling"));
        assert!(runtime.contains("Compat I/O Functions"));
        assert!(runtime.contains("Compat Time Functions"));
        assert!(runtime.contains("Compat Process Functions"));
        assert!(runtime.contains("Platform-Specific Functions"));
    }
}
